import { LightOptions } from "../light/Light";
import { LightType } from "../light/types";
    
export const LightsConfig: Record<LightType, LightOptions> = {
    PlayerLight: {
        numRays: 360,
        baseRadius: 7,
        radiusVariance: 1,
        baseAlpha: 0.5,
        alphaVariance: 0.4,
        startColor: 0x55aaff,
        endColor: 0x77edff,
        flickerAlphaDuration: 0.5,
        flickerAlphaDurationVariance: 2.5,
        flickerRadiusDuration: 0.75,
        flickerRadiusDurationVariance: 0.25,
        oscillateColorDuration: 1.5,
        oscillateColorDurationVariance: 2,
        oscillateColorDelay: 0,
        oscillateColorDelayVariance: 2,
    },
    SentryLight: {
        numRays: 360,
        baseRadius: 4,
        radiusVariance: 2,
        baseAlpha: 0.5,
        alphaVariance: 0.4,
        startColor: 0xBB32FF,
        endColor: 0x6e00a5,
        flickerAlphaDuration: 0.5,
        flickerAlphaDurationVariance: 2.5,
        flickerRadiusDuration: 1.5,
        flickerRadiusDurationVariance: 0.5,
        oscillateColorDuration: 1.5,
        oscillateColorDurationVariance: 2,
        oscillateColorDelay: 0,
        oscillateColorDelayVariance: 2,
    },
    ExitLight: {
        numRays: 360,
        baseRadius: 10,
        radiusVariance: 5,
        baseAlpha: 0.5,
        alphaVariance: 0.4,
        startColor: 0x2ddf03,
        endColor: 0x27ffc3,
        flickerAlphaDuration: 0.5,
        flickerAlphaDurationVariance: 2.5,
        oscillateColorDuration: 1.5,
        oscillateColorDurationVariance: 2,
        oscillateColorDelay: 0,
        oscillateColorDelayVariance: 2,
    },
    TorchLight: {
        numRays: 360,
        baseRadius: 10,
        radiusVariance: 2.5,
        baseAlpha: 0.5,
        alphaVariance: 0.4,
        startColor: 0xdfb503,
        endColor: 0xab3347,
        flickerAlphaDuration: 0.5,
        flickerAlphaDurationVariance: 2.5,
        oscillateColorDuration: 1.5,
        oscillateColorDurationVariance: 2,
        oscillateColorDelay: 0,
        oscillateColorDelayVariance: 2,
    },
    AntiLight: {
        numRays: 360,
        baseRadius: 5,
        radiusVariance: 2,
        baseAlpha: 0.7,
        alphaVariance: 0.3,
        startColor: 0xff0022,
        endColor: 0xff2244,
        flickerAlphaDuration: 0.5,
        flickerAlphaDurationVariance: 2.5,
        oscillateColorDuration: 0.5,
        oscillateColorDurationVariance: 3,
        oscillateColorDelay: 0,
        oscillateColorDelayVariance: 1,
    },
    SwitchLight: {
        numRays: 360,
        baseRadius: 5,
        radiusVariance: 1,
        baseAlpha: 0.5,
        alphaVariance: 0.4,
        startColor: 0x4556ff,
        endColor: 0x0000ab,
        flickerAlphaDuration: 0.5,
        flickerAlphaDurationVariance: 2.5,
        oscillateColorDuration: 1.5,
        oscillateColorDurationVariance: 2,
        oscillateColorDelay: 0,
        oscillateColorDelayVariance: 2,
    },
}